# Generated by Django 5.0.3 on 2024-03-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ldata_sdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sdata',
            old_name='fname',
            new_name='fnm',
        ),
        migrations.RenameField(
            model_name='sdata',
            old_name='lname',
            new_name='lnm',
        ),
    ]
